/*
name: 001_Setup.sql
description : 環境をセットアップするSQL
*/

-- 環境構築ができる管理者権限を使用
USE ROLE ACCOUNTADMIN;

-- データベースの作成
CREATE DATABASE IF NOT EXISTS TITANIC_DB;

-- スキーマの作成
CREATE SCHEMA IF NOT EXISTS TITANIC_DB.STAGE
  COMMENT = 'データ取込層：外部ファイルの一時置き場（Stageオブジェクトを管理）';

CREATE SCHEMA IF NOT EXISTS TITANIC_DB.BRONZE
  COMMENT = '生データ格納層：外部ソースからのデータをそのまま保持する（変換・加工なし）';

CREATE SCHEMA IF NOT EXISTS TITANIC_DB.SILVER
  COMMENT = '加工データ層：クレンジング・型変換・特徴量エンジニアリング済みのデータ';

CREATE SCHEMA IF NOT EXISTS TITANIC_DB.GOLD
  COMMENT = '分析・提供層：MLモデルの予測結果・集計済みデータ（BIツールやアプリが参照する）';

-- ウェアハウスの作成
CREATE WAREHOUSE IF NOT EXISTS TITANIC_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'TITANIC DB用のWH';

-- SYSADMINへ所有権を移譲
GRANT OWNERSHIP ON DATABASE TITANIC_DB TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TITANIC_DB.STAGE TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TITANIC_DB.BRONZE TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TITANIC_DB.SILVER TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA TITANIC_DB.GOLD TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON WAREHOUSE TITANIC_WH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;