/*
name: 002_Load_Stage.sql
description: 内部STAGEとFILE FORMATを作成する
*/
-- セッション設定
USE ROLE SYSADMIN;
USE DATABASE TITANIC_DB;
USE SCHEMA TITANIC_DB.STAGE;
USE WAREHOUSE TITANIC_WH;

-- FILE FORMATの作成
CREATE OR REPLACE FILE FORMAT TITANIC_DB.STAGE.FMT_CSV_TITANIC
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  PARSE_HEADER = TRUE
  COMMENT = 'タイタニックCSV用のファイルフォーマット';

-- 内部ステージの作成
-- フォルダ構造:
--   STG_TITANIC/data/    ← CSVデータ置き場
--   STG_TITANIC/python/  ← Pythonファイル置き場
CREATE STAGE IF NOT EXISTS TITANIC_DB.STAGE.STG_TITANIC
  FILE_FORMAT = (FORMAT_NAME = 'TITANIC_DB.STAGE.FMT_CSV_TITANIC')
  COMMENT = 'タイタニックプロジェクト用ステージ';