/*
name: 003_Stage_to_Bronze.sql
description: STAGEの内部StageからCSVファイルをロードする
*/
-- セッション設定
USE ROLE SYSADMIN;
USE DATABASE TITANIC_DB;
USE SCHEMA TITANIC_DB.BRONZE;
USE WAREHOUSE TITANIC_WH;

-- CSVからスキーマを推論してBRONZEテーブルを作成
CREATE TABLE IF NOT EXISTS TITANIC_DB.BRONZE.RAW_TITANIC
  COMMENT = 'タイタニック乗客データ（生データ）'
  USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
      INFER_SCHEMA(
        LOCATION => '@TITANIC_DB.STAGE.STG_TITANIC/data/',
        FILE_FORMAT => 'TITANIC_DB.STAGE.FMT_CSV_TITANIC',
        IGNORE_CASE => TRUE
      )
    )
  );

-- 推論結果の確認
DESC TABLE TITANIC_DB.BRONZE.RAW_TITANIC;

-- STAGEからBRONZEにロード
COPY INTO TITANIC_DB.BRONZE.RAW_TITANIC
  FROM @TITANIC_DB.STAGE.STG_TITANIC/data/
  FILE_FORMAT = (FORMAT_NAME = 'TITANIC_DB.STAGE.FMT_CSV_TITANIC')
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  ON_ERROR = 'CONTINUE';

-- 確認
SELECT * FROM TITANIC_DB.BRONZE.RAW_TITANIC LIMIT 10;
SELECT COUNT(*) AS ROW_COUNT FROM TITANIC_DB.BRONZE.RAW_TITANIC;